In [2]:
import pandas as pd
import numpy as np
import sys, os
sys.path.append(os.path.abspath('..'))

In [3]:
data_json = pd.read_json('../outputs/preprocessed/train_data.json')
data_train = pd.read_csv('../data/MELD.Raw/train/train_sent_emo.csv')

In [4]:
data_json['filename'] = data_json['audio'].apply(lambda x: x.split("audio\\")[-1])

In [5]:
data_json.head()

,video,audio,text,label,filename
0,..\data\MELD.Raw\train\train_splits\dia0_utt0.mp4,..\data\MELD.Raw\train\audio\dia0_utt0.wav,also I was the point person on my companys tr...,neutral,dia0_utt0.wav
1,..\data\MELD.Raw\train\train_splits\dia0_utt1.mp4,..\data\MELD.Raw\train\audio\dia0_utt1.wav,You mustve had your hands full.,neutral,dia0_utt1.wav
2,..\data\MELD.Raw\train\train_splits\dia0_utt2.mp4,..\data\MELD.Raw\train\audio\dia0_utt2.wav,That I did. That I did.,neutral,dia0_utt2.wav
3,..\data\MELD.Raw\train\train_splits\dia0_utt3.mp4,..\data\MELD.Raw\train\audio\dia0_utt3.wav,So lets talk a little bit about your duties.,neutral,dia0_utt3.wav
4,..\data\MELD.Raw\train\train_splits\dia0_utt4.mp4,..\data\MELD.Raw\train\audio\dia0_utt4.wav,My duties? All right.,surprise,dia0_utt4.wav

In [6]:
data_json.shape

(9988, 5)

In [ ]:
def add_speaker(path_json, path_dataset, save_path=None):
    json_df = pd.read_json(path_json)
    dataset = pd.read_csv(path_dataset)
    json_df['filename'] = json_df['audio'].apply(lambda x: x.split("audio\\")[-1])
    for index, row in dataset.iterrows():
        filename = f"dia{row['Dialogue_ID']}_utt{row['Utterance_ID']}.wav"
        if filename in json_df['filename'].values:  
            json_df.loc[json_df['filename'] == filename, 'speaker'] = row['Speaker']

    if save_path:
        json_df.to_json(save_path)
    return json_df

train_data_json = add_speaker(path_json='../outputs/preprocessed/train_data.json', path_dataset='../data/MELD.Raw/train/train_sent_emo.csv', save_path='../outputs/preprocessed/train_data_speaker.json') 
test_data_json = add_speaker(path_json='../outputs/preprocessed/test_data.json', path_dataset='../data/MELD.Raw/test_sent_emo.csv', save_path='../outputs/preprocessed/test_data_speaker.json')
dev_data_json = add_speaker(path_json='../outputs/preprocessed/dev_data.json', path_dataset='../data/MELD.Raw/dev_sent_emo.csv', save_path='../outputs/preprocessed/dev_data_speaker.json')

In [56]:
train_data_json

,video,audio,text,label,filename,speaker
0,..\data\MELD.Raw\train\train_splits\dia0_utt0.mp4,..\data\MELD.Raw\train\audio\dia0_utt0.wav,also I was the point person on my companys tr...,neutral,dia0_utt0.wav,Chandler
1,..\data\MELD.Raw\train\train_splits\dia0_utt1.mp4,..\data\MELD.Raw\train\audio\dia0_utt1.wav,You mustve had your hands full.,neutral,dia0_utt1.wav,The Interviewer
2,..\data\MELD.Raw\train\train_splits\dia0_utt2.mp4,..\data\MELD.Raw\train\audio\dia0_utt2.wav,That I did. That I did.,neutral,dia0_utt2.wav,Chandler
3,..\data\MELD.Raw\train\train_splits\dia0_utt3.mp4,..\data\MELD.Raw\train\audio\dia0_utt3.wav,So lets talk a little bit about your duties.,neutral,dia0_utt3.wav,The Interviewer
4,..\data\MELD.Raw\train\train_splits\dia0_utt4.mp4,..\data\MELD.Raw\train\audio\dia0_utt4.wav,My duties? All right.,surprise,dia0_utt4.wav,Chandler
...,...,...,...,...,...,...
9983,..\data\MELD.Raw\train\train_splits\dia1038_ut...,..\data\MELD.Raw\train\audio\dia1038_utt13.wav,You or me?,neutral,dia1038_utt13.wav,Chandler
9984,..\data\MELD.Raw\train\train_splits\dia1038_ut...,..\data\MELD.Raw\train\audio\dia1038_utt14.wav,"I got it. Uh, Joey, women don't have Adam's ap...",neutral,dia1038_utt14.wav,Ross
9985,..\data\MELD.Raw\train\train_splits\dia1038_ut...,..\data\MELD.Raw\train\audio\dia1038_utt15.wav,"You guys are messing with me, right?",surprise,dia1038_utt15.wav,Joey
9986,..\data\MELD.Raw\train\train_splits\dia1038_ut...,..\data\MELD.Raw\train\audio\dia1038_utt16.wav,Yeah.,neutral,dia1038_utt16.wav,All
9987,..\data\MELD.Raw\train\train_splits\dia1038_ut...,..\data\MELD.Raw\train\audio\dia1038_utt17.wav,"That was a good one. For a second there, I was...",joy,dia1038_utt17.wav,Joey

**Load tensors data**

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader


data = torch.load(os.path.join("..", "outputs", "embeddings", "loaders_datasets.pt"))
data

{'train': {'audio': <torch.utils.data.dataset.TensorDataset at 0x24a8a25eca0>,
  'text': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d760>,
  'video': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d3d0>,
  'labels': tensor([0, 0, 0,  ..., 6, 0, 1])},
 'val': {'audio': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d6d0>,
  'text': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d490>,
  'video': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d730>,
  'labels': tensor([4, 6, 0,  ..., 4, 4, 4])},
 'test': {'audio': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d4c0>,
  'text': <torch.utils.data.dataset.TensorDataset at 0x24a8461c790>,
  'video': <torch.utils.data.dataset.TensorDataset at 0x24a8449f7c0>,
  'labels': tensor([6, 2, 0,  ..., 0, 0, 0])}}

**Embedding of Speakers**

In [86]:
import torch
import pandas as pd

# train ../outputs/preprocessed/train_data_speaker.json
# dev ../outputs/preprocessed/dev_data_speaker.json
# test ../outputs/preprocessed/test_data_speaker.json


def embedding_speaker(json_path, data, split=None):
    json_df = pd.read_json(json_path)
    if split in data:
        speakers_to_idx = {speaker: i for i, speaker in enumerate(json_df['speaker'].unique())}
        speaker_labels = [speakers_to_idx[speaker] for speaker in json_df['speaker']]
        data[split]['speaker'] = torch.tensor(speaker_labels, dtype=torch.long)

    return data

data = embedding_speaker(json_path='../outputs/preprocessed/train_data_speaker.json', data=data, split='train')
data = embedding_speaker(json_path='../outputs/preprocessed/dev_data_speaker.json', data=data, split='val')
data = embedding_speaker(json_path='../outputs/preprocessed/test_data_speaker.json', data=data, split='test')

torch.save(data, os.path.join("..", "outputs", "embeddings", "loaders_datasets_speakers.pt"))

In [87]:
data

{'train': {'audio': <torch.utils.data.dataset.TensorDataset at 0x24a8a25eca0>,
  'text': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d760>,
  'video': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d3d0>,
  'labels': tensor([0, 0, 0,  ..., 6, 0, 1]),
  'speaker': tensor([ 0,  1,  0,  ...,  2, 61,  2])},
 'val': {'audio': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d6d0>,
  'text': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d490>,
  'video': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d730>,
  'labels': tensor([4, 6, 0,  ..., 4, 4, 4]),
  'speaker': tensor([0, 1, 2,  ..., 1, 6, 1])},
 'test': {'audio': <torch.utils.data.dataset.TensorDataset at 0x24a83c3d4c0>,
  'text': <torch.utils.data.dataset.TensorDataset at 0x24a8461c790>,
  'video': <torch.utils.data.dataset.TensorDataset at 0x24a8449f7c0>,
  'labels': tensor([6, 2, 0,  ..., 0, 0, 0]),
  'speaker': tensor([0, 1, 1,  ..., 1, 3, 6])}}

In [88]:
data['train']['speaker'].shape

torch.Size([9988])

In [89]:
import torch
print(torch.version.cuda)  # Affiche la version de CUDA utilisée par PyTorch
print(torch.cuda.is_available())  # Vérifie si CUDA est bien accessible

11.3
True

In [93]:
df_json = pd.read_json('../outputs/preprocessed/train_data_speaker.json')
len(df_json['speaker'].unique())

260

In [1]:
# import torch
# import torch.nn as nn
# import pandas as pd
# import numpy as np
# import sys, os
# sys.path.append(os.path.abspath('..'))
# from models.graph.graph import GraphConstructor, get_speaker_node_features, compute_adjacency_matrix, get_edge_index, get_edge_type
# from utils.dataloader import create_dataloader_with_graph_features
# from models.bigru_coattention.coattention import CoAttentionFusionWithGraph
# from pipelines.training.training_pipeline import train_coattention_graph
# import random


# seed = 42
# torch.manual_seed(seed)
# np.random.seed(seed)
# random.seed(seed)
# torch.cuda.manual_seed_all(seed)
# torch.backends.cudnn.deterministic = True
# torch.backends.cudnn.benchmark = False




# data = torch.load(os.path.join("..", "outputs", "embeddings", "loaders_datasets_speakers.pt"))
# node_features = get_speaker_node_features(data)

# train_node_features = node_features['train']
# val_node_features = node_features['val']
# test_node_features = node_features['test']

# train_adj_matrix = compute_adjacency_matrix(train_node_features)
# val_adj_matrix = compute_adjacency_matrix(val_node_features)
# test_adj_matrix = compute_adjacency_matrix(test_node_features)

# train_edge_index = get_edge_index(train_adj_matrix, threshold=0.4)
# val_edge_index = get_edge_index(val_adj_matrix, threshold=0.5)
# test_edge_index = get_edge_index(test_adj_matrix, threshold=0.5)

# train_edge_type = get_edge_type(train_edge_index, train_node_features)
# val_edge_type = get_edge_type(val_edge_index, val_node_features)
# test_edge_type = get_edge_type(test_edge_index, test_node_features)

# torch.save(data, os.path.join("..", "outputs", "embeddings", "loaders_datasets_speakers_graph.pt"))
# num_speakers = len(torch.unique(data['train']['speaker']))
# train_loaders, val_loaders, test_loaders = create_dataloader_with_graph_features(data)
# nodes_edges = {
#     'node_features': {
#         'train': train_node_features,
#         'val': val_node_features,
#         'test': test_node_features
#     },
#     'edge_index': {
#         'train': train_edge_index,
#         'val': val_edge_index,
#         'test': test_edge_index
#     },
#     'edge_type': {
#         'train': train_edge_type,
#         'val': val_edge_type,
#         'test': test_edge_type
#     }
# }
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model = CoAttentionFusionWithGraph(
#     input_dim_audio=768,
#     input_dim_text=768,
#     input_dim_video=768,
#     num_classes=7,
#     hidden_dim=128,
#     dropout_rate=0.6,
#     num_speakers=num_speakers,

# ).to(device)

# train_coattention_graph(
#     model,
#     train_loaders,
#     val_loaders,
#     num_epochs=50,
#     lr=1e-3,
#     verbose=False,
#     logfile="coattention_graph_2_aug_audio.log",
#     model_name='best_model_graph_coattention_2_aug_audio.pth',
#     num_classes=7,
#     nodes_edges=nodes_edges
# )

# model.load_state_dict(torch.load(os.path.join("best_model_graph_coattention_2_aug_audio.pth")))

# from pipelines.evaluation.evaluation_pipeline import evaluate_model_coattention_graph
# val_loss, val_accuracy, precision, recall, f1, accuracies = evaluate_model_coattention_graph(
#     model,
#     test_loaders,
#     nn.CrossEntropyLoss(),
#     device,
#     num_classes=7,
#     logfile="evaluation_log_graph_coattention__sampler",
#     node_features=nodes_edges['node_features']['test'],
#     edge_index=nodes_edges['edge_index']['test'],
#     edge_type=nodes_edges['edge_type']['test'],
#     verbose=True
# )
# print(f"Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy * 100:.2f}%, Precision: {precision * 100:.2f}%, Recall: {recall * 100:.2f}%, F1: {f1 * 100:.2f}%")


import sys, os
sys.path.append(os.path.abspath('..'))

import torch
import torch.nn as nn
from pipelines.evaluation.evaluation_pipeline import evaluate_model_coattention_graph
import pandas as pd
import numpy as np

from models.graph.graph import GraphConstructor, get_speaker_node_features, compute_adjacency_matrix, get_edge_index, get_edge_type
from utils.dataloader import create_dataloader_with_graph_features
from models.bigru_coattention.coattention import CoAttentionFusionWithGraph, CoAttentionFusion_Baseline, CoAttentionFusion_SelfAttn, CoAttentionFusion_MultiPhase, CoAttentionFusion_ModalAttention, CoAttentionFusion_Gated, CoAttentionFusion_ELRGNN, CoAttentionFusion_SelfAttn_GNN
from pipelines.training.training_pipeline import train_coattention_graph
import random


seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False




data = torch.load(os.path.join("..", "outputs", "embeddings", "loaders_datasets_speakers.pt"))
node_features = get_speaker_node_features(data)

train_node_features = node_features['train']
val_node_features = node_features['val']
test_node_features = node_features['test']

train_adj_matrix = compute_adjacency_matrix(train_node_features)
val_adj_matrix = compute_adjacency_matrix(val_node_features)
test_adj_matrix = compute_adjacency_matrix(test_node_features)

train_edge_index = get_edge_index(train_adj_matrix, threshold=0.4)
val_edge_index = get_edge_index(val_adj_matrix, threshold=0.5)
test_edge_index = get_edge_index(test_adj_matrix, threshold=0.5)

train_edge_type = get_edge_type(train_edge_index, train_node_features)
val_edge_type = get_edge_type(val_edge_index, val_node_features)
test_edge_type = get_edge_type(test_edge_index, test_node_features)

torch.save(data, os.path.join("..", "outputs", "embeddings", "loaders_datasets_speakers_graph.pt"))
num_speakers = len(torch.unique(data['train']['speaker']))
train_loaders, val_loaders, test_loaders = create_dataloader_with_graph_features(data)
nodes_edges = {
    'node_features': {
        'train': train_node_features,
        'val': val_node_features,
        'test': test_node_features
    },
    'edge_index': {
        'train': train_edge_index,
        'val': val_edge_index,
        'test': test_edge_index
    },
    'edge_type': {
        'train': train_edge_type,
        'val': val_edge_type,
        'test': test_edge_type
    }
}
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


models = {
    "Baseline_BiGRU": CoAttentionFusion_Baseline,
    "BiGRU_SelfAttn": CoAttentionFusion_SelfAttn,
    "BiGRU_selfAttnGNN":CoAttentionFusion_SelfAttn_GNN,
    "Fusion_MultiPhase": CoAttentionFusion_MultiPhase,
    "Modal_Attention": CoAttentionFusion_ModalAttention,
    "Gated_Fusion": CoAttentionFusion_Gated,
    "ELR_GNN": CoAttentionFusion_ELRGNN,
}

results = {}

num_epochs = 50
learning_rate = 1e-3
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# **Boucle sur toutes les approches**
for model_name, ModelClass in models.items():
    print(f"\n🔄 Entraînement du modèle : {model_name}")

    # **Initialisation du modèle**
    model = ModelClass(
        input_dim_audio=768,
        input_dim_text=768,
        input_dim_video=768,
        num_classes=7,
        hidden_dim=128
    ).to(device)

    # **Entraînement**
    model_save_path = f"best_model_{model_name}.pth"
    train_coattention_graph(
        model,
        train_loaders,
        val_loaders,
        num_epochs=num_epochs,
        lr=learning_rate,
        verbose=False,
        logfile=f"{model_name}_training.log",
        model_name=model_save_path,
        num_classes=7,
        nodes_edges=nodes_edges
    )

    model.load_state_dict(torch.load(model_save_path, map_location=device))

    # **Évaluation**
    print(f"\n Évaluation du modèle : {model_name}")
    best_model_path = os.path.join('..', '..', 'outputs', 'models', model_name)

    val_loss, val_accuracy, precision, recall, f1, accuracies = evaluate_model_coattention_graph(
        model,
        test_loaders,
        nn.CrossEntropyLoss(),
        device,
        num_classes=7,
        logfile=f"{best_model_path}_evaluation.log",
        node_features=nodes_edges['node_features']['test'],
        edge_index=nodes_edges['edge_index']['test'],
        edge_type=nodes_edges['edge_type']['test'],
        verbose=True
    )

    results[model_name] = {
        "Validation Loss": val_loss,
        "Validation Accuracy": val_accuracy * 100,
        "Precision": precision * 100,
        "Recall": recall * 100,
        "F1 Score": f1 * 100
    }

    print(f"\n🔍 Résultats pour {model_name}:")
    print(f"Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy * 100:.2f}%, "
          f"Precision: {precision * 100:.2f}%, Recall: {recall * 100:.2f}%, F1 Score: {f1 * 100:.2f}%")

# **Affichage des performances de toutes les approches**
print("\n📊 Comparaison des performances des modèles :")
for model_name, metrics in results.items():
    print(f"\n🔹 {model_name}:")
    for metric, value in metrics.items():
        print(f"   {metric}: {value:.2f}%")

c:\Users\admin\anaconda3\envs\mer-gpu\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🔄 Entraînement du modèle : Baseline_BiGRU

Epoch 1/50 - Training:   0%|          | 0/313 [00:00<?, ?it/s]

 Graph output shape: torch.Size([260, 128])

Epoch 1/50 - Training:   0%|          | 0/313 [00:01<?, ?it/s]

RuntimeError: Tensors must have same number of dimensions: got 1 and 2